version: '3.8'
services:
  authservice:
    image: authservice:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=authdb;User=sa;Password=poc_aws;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "poc_aws"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

